# Learning Python >3.5 on Notebook
Tecnun - UNAV
Winter Course 2019 <p>
drosquete@ceit.es

## We have done
* Installed Python
* Started Ipython Notebook

# Getting started with Python

In [1]:
print ('Hello World!')

Hello World!


## Create some variables in Python

In [2]:
i = 4  #int
i

4

In [3]:
type(i)

int

In [4]:
f = 4.1  #float

In [5]:
type(f)

float

In [6]:
b = True  #boolean variable

In [7]:
s = "This is a string!"

In [8]:
print (s)

This is a string!


## Using python as a calculator

In [9]:
2+2

4

In [10]:
i+3

7

In [11]:
## Pow
2 ** 4

16

In [12]:
# Float division
7 / 3

2.3333333333333335

In [13]:
# Integer division
7 // 3 

2

### Operator _

This operator takes the previous calculated value and operates with it as this symbol _

In [14]:
_ * 8

16

## What about strings?

In [15]:
"Hola" + " " + "mundo"

'Hola mundo'

Even without the +, they concatenate if they are strings explicitly. It <b>DOES NOT</b> work on variables.

In [16]:
"Hola" " " "mundo"

'Hola mundo'

In [17]:
print ("Hola \nMundo")

Hola 
Mundo


Sometimes is necessary to print as is. Raw data puts an r as prefix to the string

In [18]:
print (r"Hola \nMundo")

Hola \nMundo


String manipulation is also allowed. Put the variable name, followed by the dot, and hit "tab". It will show you all the options

In [19]:
pal = "Hola Mundo"

In [20]:
pal.upper()

'HOLA MUNDO'

In [21]:
pal.count("o")

2

In [22]:
pal.count("O")

0

What about if I want just 1 letter or a range of letters?

In [23]:
pal[3]

'a'

In [24]:
pal[0:3]

'Hol'

In [25]:
pal[-7:-2]

'a Mun'

The next one won't work because the indexes must be all negative or all positives

In [26]:
pal[-7:2]

''

In [27]:
pal[-2:]

'do'

In [28]:
pal[:2]

'Ho'

In [29]:
len(pal)

10

## Advanced python types

In [30]:
l = [3,1,2]  #list

In [31]:
print (l)

[3, 1, 2]


In [32]:
d = {'foo':1, 'bar':2.3, 's':'my first dictionary'}  #dictionary

In [33]:
print (d)

{'foo': 1, 'bar': 2.3, 's': 'my first dictionary'}


In [34]:
print (d['foo'])  #element of a dictionary

1


In [35]:
n = None  #Python's null type

In [36]:
type(n)

NoneType

## Advanced printing

In [37]:
print ("Our float value is %s. Our int value is %s." % (f,i))  #Python is pretty good with strings!

Our float value is 4.1. Our int value is 4.


## Conditional statements in python

First, when setting a conditional or a loop, the line must end on ":".<p>Note that in Python, we don't use {} or other symbols to indicate the part of the loop that gets iterated.  Instead, we just indent and align each of the iterated statements with spaces or tabs. (You can use as many as you want, as long as the lines are aligned.)

In [38]:
if i == 1 and f > 4:
    print ("The value of i is 1 and f is greater than 4.")
elif i > 4 or f > 4:
    print ("i or f are greater than 4.")
else:
    print ("both i and f are less than or equal to 4")


i or f are greater than 4.


## Loops

In [39]:
print (l)

[3, 1, 2]


In [40]:
for e in l:
    print (e)

3
1
2


In [41]:
for i in range(0, 5):
    print(i)

0
1
2
3
4


In [42]:
counter = 6
while counter < 10:
    print (counter)
    counter += 1

6
7
8
9


# Creating functions in Python

Again, we don't use {}, but just indent the lines that are part of the function.

In [43]:
def add2(x):
    y = x + 2
    return y

In [44]:
i = 5

In [45]:
add2(i)

7

We can also define simple functions with lambda functions:

In [46]:
square = lambda x: x*x

In [47]:
square(3)

9

In [48]:
def divide(x,y):
    return x/y

In [49]:
def divisor(d):
    return lambda x: divide(x,d)

In [50]:
half=divisor(2)
third=divisor(3)

In [51]:
print(half(32),third(32))

16.0 10.666666666666666


## Does python uses arrays?
Trust me... you didn't want to ask that... Yes it does, it's the lists (or the array.array), but they are so limited, it hurts!!! so let's use the numpy arrays! <p>
<p> NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axis. The number of axis is rank.<p>
<p>
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. The numpy arrays are called <i>ndarray</i>
</p><b>First step: </b> import numpy library

In [52]:
import numpy as np

Let's meet our friend the function arange. It allows you to generate numbers equally spaced and store it on a ndarray

In [53]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

You can change the parameters, in this case, start, stop and step_size

In [54]:
np.arange(0,12,3)

array([0, 3, 6, 9])

Using this tool will make easier to generate multidimensional arrays to process in the following

In [55]:
firstArray = np.arange(0,40,2)

In [56]:
firstArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

### New operator. ::

The operator :: works for slicing arrays. with this premise:  'nothing for the first argument, nothing for the second, and jump by third'

In [57]:
print(firstArray[::3])
print(firstArray[::2])

[ 0  6 12 18 24 30 36]
[ 0  4  8 12 16 20 24 28 32 36]


Inverse operator is slicing -1

In [58]:
firstArray[::-1]

array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,
        4,  2,  0])

Let's suppose we want to consult each 2 elements on a sequential array, from the position 4 until the end.

In [59]:
print(np.arange(0,40)[4::2])

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


Let's suppose we want to consult each 2 arrays on a sequential matrix.<p>
Basically, I generate an array of 40 elements from 0 to 39, then reshape (<b>Explained in line 61</b>) it in a 4,10 matrix, finally apply the slicing operator each 2 rows

In [60]:
print(np.arange(0,40).reshape(4,10)[::2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]]


Now in columns. There is a notation change. You must take in consideration that in matrix notation you have 2 sides when consulting or modifying elements [RowSide,ColumnSide]

In [61]:
print(np.arange(0,40).reshape(4,10)[::,::2])

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


Let's create now a matrix with dimensions 4,5 with this array

In [62]:
firstMatrix = firstArray.reshape(4,5)

In [63]:
firstMatrix

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [64]:
firstMatrix.shape

(4, 5)

In [65]:
firstMatrix.ndim

2

In [66]:
firstMatrix.size

20

In [67]:
type(firstMatrix)

numpy.ndarray

It is possible to create a ndarray from a list or regular array from python, as follows

In [68]:
secondArray = np.array([1,2,3])

In [69]:
type(secondArray)

numpy.ndarray

In [70]:
secondArray[1]

2

In [71]:
secondMatrix = np.array([(1.2,2.4,5),(2,3,4)])

In [72]:
secondMatrix

array([[1.2, 2.4, 5. ],
       [2. , 3. , 4. ]])

In [73]:
thirdArray = np.zeros((2,3))

In [74]:
thirdArray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
fourthArray = np.ones((2,3))

In [76]:
fourthArray

array([[1., 1., 1.],
       [1., 1., 1.]])

In this case, empty may result on undetermined values on each cell

In [77]:
fifthArray = np.empty((2,3))

In [78]:
fifthArray

array([[1., 1., 1.],
       [1., 1., 1.]])

Elevate each number in the matrix to square

In [79]:
secondMatrix ** 2

array([[ 1.44,  5.76, 25.  ],
       [ 4.  ,  9.  , 16.  ]])

Evaluate which cells accomplish a condition

In [80]:
secondMatrix < 2.5

array([[ True,  True, False],
       [ True, False, False]])

What if I want to add all the values in secondMatrix <b>rows</b> that accomplish a condition?

In [81]:
np.sum(secondMatrix < 2.5, axis = 0)

array([2, 1, 0])

What if I want to add all the values in secondMatrix <b>columns</b> that accomplish a condition?

In [82]:
np.sum(secondMatrix < 2.5, axis = 1)

array([2, 1])

### Random generator
Numpy incorporates a random generator that returns a ndarray in the shape you indicate. But first, remember to initialize the seed, so we can have always the same results

In [83]:
np.random.seed(1234)

In [84]:
thirdMatrix = np.random.random((3,4))

There are other operations as np.random.rand() that receives initial value, final value and dimensions. F.E.: 0,10,(2,5). This will create a matrix of 2x5 with random values from 0 to 9

In [85]:
thirdMatrix

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858],
       [0.77997581, 0.27259261, 0.27646426, 0.80187218],
       [0.95813935, 0.87593263, 0.35781727, 0.50099513]])

Transpose

In [86]:
thirdMatrix.T

array([[0.19151945, 0.77997581, 0.95813935],
       [0.62210877, 0.27259261, 0.87593263],
       [0.43772774, 0.27646426, 0.35781727],
       [0.78535858, 0.80187218, 0.50099513]])

Inverse

In [87]:
np.linalg.inv(np.random.random((3,3)))

array([[  9.39577824,   3.65841084,  -9.67196545],
       [-10.64094157,  -2.01457181,  10.87340801],
       [  5.83970303,  -2.87534538,  -3.07648268]])

Comparing Matrices

In [88]:
thirdMatrix.T is thirdMatrix

False

### Using boolean indexes in a matrix
One of the most used operations in ML is to obtain values on big data matrix using a condition. Therefor, is important to handle the next operation very well.

In [89]:
import numpy as np
fourthMatrix = np.arange(12).reshape(3,4)

In [90]:
fourthMatrix = fourthMatrix *2

In [91]:
fourthMatrix

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [92]:
booleanIndexes = fourthMatrix > 4

In [93]:
booleanIndexes

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
fourthMatrix[booleanIndexes]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22])

### Knowing the index of a position in a 1D-Array from a ND-Array

In [95]:
np.unravel_index(6,fourthMatrix.shape)

(1, 2)

In [96]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)